# We can also use a docker container an run our stop in himself.
name: 003Easy
run-name: 003easy_runname
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: node app.js
      
    
